config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :gonzo

end

app/models/gonzo.rb
class Gonzo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gonzo_controller.rb
class GonzoController < ApplicationController
	def index
		@gonzos = Gonzo.all
	end

	def show
		@gonzo = Gonzo.find(params[:id])
	end

	def new
		@gonzo = Gonzo.new
	end

	def gonzos_params
		params.require(:gonzo).permit(:title, :body)
	end

	def create
		@gonzo = Gonzo.new(gonzos_params)
			
		if @gonzo.save
			redirect_to gonzos_path, :notice => "Your new Gonzo was created!"
		else
			render "new"
		end
	end

	def edit
		@gonzo = Gonzo.find(params[:id])
	end

	def update
		@gonzo = Gonzo.find(params[:id])

		if @gonzo.update_attributes(gonzos_params)
			redirect_to gonzos_path, :notice => "Your Gonzo was updated!"
		else
			render "edit"
		end
	end

	def destroy
		@gonzo = Gonzo.find(params[:id])
		@gonzo.destroy

		redirect_to gonzos_path, :notice => "Your Gonzo was deleted!"
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to :controller => 'gonzo', :action => 'index'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gonzo_helper.rb
module GonzoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gonzo/edit.html.erb
<h1>This is Edit</h1>

<%= form_for @gonzo do |f| %>
	<p><%= f.label :title %>: <%= f.text_field :title %></p>
	<p><%= f.label :body %>: <%= f.text_area :body %></p>
	<p><%= f.submit "Save Gonzo changes" %></p>

<% end %>

app/views/gonzo/index.html.erb
<h1>This is Index</h1>

<% @gonzos.each do |gonzo| %>

	<p>
		<%= link_to gonzo.title, gonzo %>
	</p>
	<hr />

<% end %>
<p><%= link_to "Add gonzo", new_gonzo_path %></p>

app/views/gonzo/new.html.erb
<h1>This is New</h1>

<%= form_for @gonzo do |f| %>
	<p><%= f.label :title %>: <%= f.text_field :title %></p>
	<p><%= f.label :body %>: <%= f.text_area :body %></p>
	<p><%= f.submit "Add Gonzo" %></p>

<% end %>	

app/views/gonzo/show.html.erb
<h1><%= @gonzo.title %></h1>
<p><%= @gonzo.body %></p>
<p><%= @gonzo.created_at %></p>
<p>
	<%= link_to "Edit", edit_gonzo_path(@gonzo) %>
	<%= link_to "Delete", @gonzo, :confirm => "Are you sure?", :method => :delete %>
</p>

app/views/home/index.html.erb
<h1>Welcome to Gonzo!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muppet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= flash.each do |name, message| %>
		<%= content_tag :div, :message, :id => "flash_#{name}" %>
	<% end %>

<%= yield %>

</body>
</html>